typography_spectrum: 0.9585845526307821
color:
  brandStrength: 0.20737620699219406
  lightness: 0.08971226308494806
  saturation: 0.4638335295021534
  rhythmicContrast: 0.7247254312969744
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
opengraph:
  type: Facebook Business Page
  appId: nettsideekspressen
layout_spectrum: 0.5351669827941805
author:
  name: Øyvind Paulsen
  email: post@limebox.no
  url: www.nettsideekspressen.no
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/01139bd1-7e67-42b1-a647-b8eb90511c0c.png
name: Nettsideekspressen
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0780162e-1469-42db-b8b4-707c54967452.png
